apiVersion: v1
kind: Pod
metadata:
  name: api
  labels:
    app: demo
    name: api
spec:
  containers:
    - name: html
      image: localhost:5000/api:latest
      ports:
        - name: http
          containerPort: 80
      resources:
        limits:
          memory: 256Mi
          cpu: 500m
